version: '2'
services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    ports:
        - "10013:8069"
    # run as a service
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "10013:8069"
    tty: true
    command: -- --dev=reload
    # command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    # run as a service
    restart: always
